abstract: Handling mobile location information plugin for HTTP::MobileAgent
author: Yoshiki Kurihara <kurihara at cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: HTTP-MobileAgent-Plugin-Locator
no_index: 
  directory: 
    - inc
    - t
requires: 
  Geo::Coordinates::Converter: 0
  HTTP::MobileAgent: 0
  Location::Area::DoCoMo::iArea: 0
  UNIVERSAL::can: 0
  UNIVERSAL::require: 0
version: 0.01
