--- 
abstract: Handling mobile location information plugin for HTTP::MobileAgent
author: Yoshiki Kurihara <kurihara at cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTTP-MobileAgent-Plugin-Locator
no_index: 
  directory: 
    - inc
    - t
requires: 
  Geo::Coordinates::Converter: 0
  Geo::Coordinates::Converter::iArea: 0
  HTTP::MobileAgent: 0
  UNIVERSAL::can: 0
  UNIVERSAL::require: 0
version: 0.01
